"""add models

Revision ID: 0e0a05f049db
Revises: 
Create Date: 2023-03-12 20:52:42.998520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0a05f049db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > created_at', name='valid_to_gt_created_at'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'category', 'slug', 'hash', name='uq_article_date_category_slug')
    )
    op.create_table('article_paragraphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_text', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paragraph_text', 'order', name='uq_article_paragraphs_text_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_paragraphs')
    op.drop_table('articles')
    # ### end Alembic commands ###
