"""reove article id

Revision ID: 39378ab028d7
Revises: c5d07e279b36
Create Date: 2023-03-16 22:24:19.535039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39378ab028d7'
down_revision = 'c5d07e279b36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('named_entities_article_id_fkey', 'named_entities', type_='foreignkey')
    op.drop_column('named_entities', 'article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('named_entities', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('named_entities_article_id_fkey', 'named_entities', 'articles', ['article_id'], ['id'])
    # ### end Alembic commands ###
