"""add named entity table

Revision ID: 5e06a4a5dc23
Revises: 8a3c2c69caef
Create Date: 2023-03-16 21:55:07.800584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e06a4a5dc23'
down_revision = '8a3c2c69caef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_named_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_text', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_named_entities')
    # ### end Alembic commands ###
