"""add vec col

Revision ID: 6fa57ba009c7
Revises: e2fe21746179
Create Date: 2023-03-15 21:10:19.428702

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = "6fa57ba009c7"
down_revision = "e2fe21746179"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("embedding", Vector(dim=1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "embedding")
    # ### end Alembic commands ###
