"""change vector dim

Revision ID: 824b75e2afda
Revises: 39378ab028d7
Create Date: 2023-03-19 17:04:03.487144

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = "824b75e2afda"
down_revision = "39378ab028d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article_paragraphs", "embedding")
    op.drop_column("article_summaries", "embedding")

    op.add_column(
        "article_paragraphs",
        sa.Column("embedding", Vector(dim=768), nullable=True),
    )

    op.add_column(
        "article_summaries",
        sa.Column("embedding", Vector(dim=768), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("article_paragraphs", "embedding")
    op.drop_column("article_summaries", "embedding")

    op.add_column(
        "article_paragraphs",
        sa.Column("embedding", Vector(dim=1536), nullable=True),
    )

    op.add_column(
        "article_summaries",
        sa.Column("embedding", Vector(dim=1536), nullable=True),
    )
    # ### end Alembic commands ###
