"""change uq constraint on ArticleP

Revision ID: 862d1aabf9c4
Revises: 6fa57ba009c7
Create Date: 2023-03-15 21:55:21.058941

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "862d1aabf9c4"
down_revision = "6fa57ba009c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_article_paragraphs_text_order", "article_paragraphs", type_="unique"
    )
    op.create_unique_constraint(
        "uq_article_paragraphs_text_order",
        "article_paragraphs",
        ["paragraph_text", "order", "article_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_article_paragraphs_text_order", "article_paragraphs", type_="unique"
    )
    op.create_unique_constraint(
        "uq_article_paragraphs_text_order",
        "article_paragraphs",
        ["paragraph_text", "order"],
    )
    # ### end Alembic commands ###
