"""remove silly model

Revision ID: e2fe21746179
Revises: 26b0f0976c34
Create Date: 2023-03-13 22:10:10.663436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fe21746179'
down_revision = '26b0f0976c34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='foos_pkey')
    )
    # ### end Alembic commands ###
