name: Chatting with the Guardian

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
    - run: |
        invoke install-dependencies
    - name: Lint with flake8
      run: |
        invoke lint 
    - name: Test with pytest
      run: |
        invoke test
    - name: Run Migrations
      run: |
        invoke run_migrations --prod=TRUE --database-url=${{ secrets.DATABASE_URL }}
