name: Chatting with the Guardian

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry -vvv install --with dev
    - run: |
        poetry run invoke lint 
    - run: |
        poetry run invoke test
    - run: |
        poetry run invoke run-migrations --prod=TRUE --database-url=${{ secrets.DATABASE_URL }}
